### ISSUE TITLE
[Security] Hash passwords before storing into DB

### ISSUE THREAD

**Issue by GlennTatum** [tchitrakorn/Mingly#8]
# Issue: Passwords are being stored in plain text

Storing passwords in plain can get an attacker to get access to users password if the database is compromised.

For storing passwords the process should be the following:

Get password -> Hash -> Store in DB

For retrieving passwords:

Get Password -> Hash -> Compare the password hash against user password hash in the database (This verifies if the users password entry was correct)

https://github.com/tchitrakorn/Mingly/blob/b3239b23686f33866d77d61b551d802d4a203b4b/server/index.js#L25-L32

https://github.com/tchitrakorn/Mingly/blob/b3239b23686f33866d77d61b551d802d4a203b4b/server/index.js#L17-L23

**Comment by tchitrakorn** [comment]
Thank you for bringing it to my attention! I will make some improvements on this!
